#!/usr/bin/env node

/**
 * Prebuild script that auto-increments the build number
 * and updates version.ts before each build.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const BUILD_NUMBER_FILE = resolve("build-number.txt");
const VERSION_FILE = resolve("src/version.ts");

// Read current build number
let buildNumber = 0;
try {
  const content = readFileSync(BUILD_NUMBER_FILE, "utf8").trim();
  buildNumber = parseInt(content, 10) || 0;
} catch {
  // File doesn't exist, start at 0
}

// Increment build number
buildNumber++;

// Write new build number
writeFileSync(BUILD_NUMBER_FILE, `${buildNumber}\n`);

// Update version.ts with new build number
const versionContent = `/**
 * Build information for FBI (Factorio Blueprint Investigator)
 * This file is auto-generated by prebuild.mjs - do not edit manually
 */
export const BUILD_NUMBER = ${buildNumber};
`;

writeFileSync(VERSION_FILE, versionContent);

console.log(`Build number incremented to ${buildNumber}`);
