/**
 * Build information for FBI (Factorio Blueprint Investigator)
 * 
 * ============================================
 * WARNING: AUTO-GENERATED FILE - DO NOT EDIT!
 * This file is regenerated by prebuild.mjs on each build.
 * ============================================
 */
export const BUILD_NUMBER = 5;
